manifest:
  # This west.yml requires west 0.12s or later, because the "import"
  # feature used below was introduced then.
  version: 0.12

  # "projects" is a list of git repositories which make up the project
  projects:
    - name: zephyr
      url: git@github-personal:stemschmidt/zephyr.git
      revision: tlv320dac3100
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nordic
          - mbedtls
          - mbedtls-3.6
          - segger
          - tf-psa-crypto
          - zephyr
  
  self:
    # This repository should be cloned to application.
    path: application
